version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_local
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_local:/home/node/.n8n
    environment:
      GENERIC_TIMEZONE: "America/Sao_Paulo"
    restart: unless-stopped
